### ISSUE TITLE
tflite-runtime error

### ISSUE THREAD

**Issue by AhDiego** [JuliaPoo/AsciiArtist#3]
Each time I try to install this module on python (3.11), this happens:
![image](https://github.com/JuliaPoo/AsciiArtist/assets/116313580/1e0913cd-493c-43f1-b2a7-9cf0a8bd671b)
so I tried installing it from the .whl file and this happened:
![image](https://github.com/JuliaPoo/AsciiArtist/assets/116313580/ed02e60b-69b3-4938-9ecb-428581bda4eb)

So if I try this on 3.8, would it work?

**Comment by JuliaPoo** [comment]
Hi yes, the supported versions are 3.7 to 3.9, and the reason is because tflite-runtime is unmaintained. I intend to port the runtime to numpy some time in the future

**Comment by AhDiego** [comment]
Oh okay, thanks very much for the help and sorry for the late reply, also 3.8 worked with me.
